// connect.js — Standalone mode: connection screen + server URL management
import { setState } from "./state.js"

const STORAGE_KEY = "pilot_connection"

export function getConnection() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    return stored ? JSON.parse(stored) : null
  } catch {
    return null
  }
}

export function saveConnection(serverUrl, token) {
  localStorage.setItem(
    STORAGE_KEY,
    JSON.stringify({ serverUrl, token, savedAt: Date.now() })
  )
  setState({ serverUrl, token })
}

export function clearConnection() {
  localStorage.removeItem(STORAGE_KEY)
  setState({ serverUrl: null, token: null })
}

/**
 * Parse a connect deep-link from the URL hash.
 * Format: #connect=<base64(serverUrl|token)>
 * The QR code generated by the banner encodes this format.
 */
export function parseConnectHash() {
  const hash = location.hash.slice(1)
  const params = new URLSearchParams(hash)
  const connect = params.get("connect")
  if (!connect) return null

  try {
    const decoded = atob(connect)
    const sep = decoded.indexOf("|")
    if (sep === -1) return null
    const serverUrl = decoded.slice(0, sep)
    const token = decoded.slice(sep + 1)
    if (serverUrl && token) {
      return { serverUrl, token }
    }
  } catch {
    // malformed base64
  }
  return null
}

export function showConnectScreen() {
  const root = document.getElementById("app") || document.body
  const tokenGate = document.getElementById("token-gate")
  if (tokenGate) tokenGate.style.display = "none"

  root.style.display = "flex"
  root.innerHTML = `
    <div class="connect-screen">
      <div class="connect-card">
        <div class="connect-logo">
          <img src="./icons/icon.svg" alt="OpenCode Pilot" width="64" height="64">
          <h1>OpenCode Pilot</h1>
        </div>
        <p class="connect-subtitle">Connect to your OpenCode instance</p>

        <form id="connect-form">
          <label class="connect-label">
            Server URL
            <input
              type="url"
              id="server-url"
              class="connect-input"
              placeholder="https://xyz.trycloudflare.com"
              required
              autofocus
            >
          </label>

          <label class="connect-label">
            Token
            <input
              type="password"
              id="token"
              class="connect-input"
              placeholder="Paste your pilot token"
              required
            >
          </label>

          <button type="submit" class="btn btn-primary connect-submit">Connect</button>
        </form>

        <details class="connect-help">
          <summary>Getting started</summary>
          <ol>
            <li>Install the <a href="https://github.com/lesquel/open-remote-control" target="_blank">opencode-pilot plugin</a></li>
            <li>Run OpenCode with <code>PILOT_TUNNEL=cloudflared</code></li>
            <li>Use <code>/remote-control</code> in OpenCode to get the URL and token</li>
            <li>Or scan the QR code from the terminal — it opens this screen pre-filled</li>
          </ol>
        </details>
      </div>
    </div>
  `

  document.getElementById("connect-form").addEventListener("submit", (e) => {
    e.preventDefault()
    const serverUrl = document.getElementById("server-url").value.trim().replace(/\/$/, "")
    const token = document.getElementById("token").value.trim()
    if (!serverUrl || !token) return
    saveConnection(serverUrl, token)
    location.reload()
  })
}
